name: Staging Model Deployment for mlops-stack-aws-seek
'on':
  workflow_dispatch:
    inputs:
      modelUri:
        type: string
        description: URI of model to deploy, in the format models:/<model-name>/<version-id>
        required: true
env:
  DATABRICKS_HOST: https://e2-demo-tokyo.cloud.databricks.com
  NODE_TYPE_ID: i3.xlarge
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}
jobs:
  staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Deploy model
      env:
        MLFLOW_TRACKING_URI: databricks
      run: 'pip install mlflow

        python steps/deploy.py "${{ github.event.inputs.modelUri }}" "staging"

        '
