name: Feature and Training Integration Tests for mlops-stack-aws-seek
'on':
  workflow_dispatch: null
  pull_request:
    paths-ignore:
    - databricks-config/**
env:
  DATABRICKS_HOST: https://e2-demo-tokyo.cloud.databricks.com
  NODE_TYPE_ID: i3.2xlarge
  DATABRICKS_TOKEN: ${{secrets.STAGING_WORKSPACE_TOKEN}}
  POOL_ID: 1123-151610-opus3-pool-kohxqqz8
concurrency: mlops-stack-aws-seek-feature-training-integration-test-staging
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        pip install -r test-requirements.txt

        '
    - name: Run tests with pytest
      run: pytest
  integration_test:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build JSON job payload for integration test
      uses: actions/github-script@v6
      id: integration-test-content
      with:
        script: "const output = `\n        {\n\"run_name\": \"features-training-integration-test\"\
          ,\n\"tasks\": [\n  {\n    \"task_key\": \"pickup-features\",\n    \"notebook_task\"\
          : {\n      \"notebook_path\": \"notebooks/GenerateAndWriteFeatures\", \n\
          \      \"base_parameters\": {\n        \"env\": \"staging\",\n        \"\
          test_mode\": \"True\",\n        \"input_table_path\": \"/databricks-datasets/nyctaxi-with-zipcodes/subsampled\"\
          ,\n        \"timestamp_column\": \"tpep_pickup_datetime\",\n        \"output_table_name\"\
          : \"mlops_stack_yang_seek.trip_pickup_features_test\",\n        \"features_transform_module\"\
          : \"pickup_features\",\n        \"primary_keys\": \"zip\"\n      }\n   \
          \ },\n    \"new_cluster\": {\n      \"spark_version\": \"11.3.x-cpu-ml-scala2.12\"\
          ,\n      \"node_type_id\": \"${{ env.NODE_TYPE_ID }}\",\n      \"num_workers\"\
          : 0,\n      \"spark_conf\": {\n        \"spark.databricks.cluster.profile\"\
          : \"singleNode\",\n        \"spark.master\": \"local[*, 4]\"\n      },\n\
          \      \"custom_tags\": {\n        \"ResourceClass\": \"SingleNode\",\n\
          \        \"clusterSource\": \"mlops-stack/0.0\"\n      }\n    }\n  },\n\
          \  {\n    \"task_key\": \"dropoff-features\",\n    \"notebook_task\": {\n\
          \      \"notebook_path\": \"notebooks/GenerateAndWriteFeatures\",\n    \
          \  \"base_parameters\": {                    \n        \"env\": \"staging\"\
          ,\n        \"test_mode\": \"True\",\n        \"input_table_path\": \"/databricks-datasets/nyctaxi-with-zipcodes/subsampled\"\
          ,\n        \"timestamp_column\": \"tpep_dropoff_datetime\",\n        \"\
          output_table_name\": \"mlops_stack_yang_seek.trip_dropoff_features_test\"\
          ,\n        \"features_transform_module\": \"dropoff_features\",\n      \
          \  \"primary_keys\": \"zip\"\n      }\n    },\n    \"new_cluster\": {\n\
          \      \"spark_version\": \"11.3.x-cpu-ml-scala2.12\",\n      \"node_type_id\"\
          : \"${{ env.NODE_TYPE_ID }}\",\n      \"num_workers\": 0,\n      \"spark_conf\"\
          : {\n        \"spark.databricks.cluster.profile\": \"singleNode\",\n   \
          \     \"spark.master\": \"local[*, 4]\"\n      },\n      \"custom_tags\"\
          : {\n        \"ResourceClass\": \"SingleNode\",\n        \"clusterSource\"\
          : \"mlops-stack/0.0\"\n      }\n    }\n  },\n  {\n    \"task_key\": \"training\"\
          ,\n    \"depends_on\": [\n      {\n        \"task_key\": \"dropoff-features\"\
          \n      },\n      {\n        \"task_key\": \"pickup-features\"\n      }\n\
          \    ],\n    \"notebook_task\": {\n      \"notebook_path\": \"notebooks/TrainWithFeatureStore\"\
          ,\n      \"base_parameters\": {\n        \"env\": \"test\",\n        \"\
          test_mode\": \"True\",\n        \"training_data_path\": \"/databricks-datasets/nyctaxi-with-zipcodes/subsampled\"\
          ,\n        \"experiment_name\": \"/mlops-stack-aws-seek/mlops-stack-aws-seek-experiment-test\"\
          ,\n        \"model_name\": \"mlops-stack-aws-seek-model-test\"\n      }\n\
          \    },\n    \"new_cluster\": {\n      \"spark_version\": \"11.3.x-cpu-ml-scala2.12\"\
          ,\n      \"node_type_id\": \"${{ env.NODE_TYPE_ID }}\",\n      \"num_workers\"\
          : 0,\n      \"spark_conf\": {\n        \"spark.databricks.cluster.profile\"\
          : \"singleNode\",\n        \"spark.master\": \"local[*, 4]\"\n      },\n\
          \      \"custom_tags\": {\n        \"ResourceClass\": \"SingleNode\",\n\
          \        \"clusterSource\": \"mlops-stack/0.0\"\n      }\n    }\n  }\n],\n\
          \"git_source\": {\n  \"git_url\": \"${{ github.server_url }}/${{ github.repository\
          \ }}\",\n  \"git_provider\": \"gitHub\",\n  \"git_commit\": \"${{ github.event.pull_request.head.sha\
          \ || github.sha }}\"\n},\n\"access_control_list\": [\n  {\n    \"group_name\"\
          : \"mlopsusers\",\n    \"permission_level\": \"CAN_VIEW\"\n  }\n]\n}`\n\
          return output.replace(/\\r?\\n|\\r/g, '')    \n"
    - name: Feature Store/Model Training Integration Test
      id: features-training-integration-test
      run: "python -m pip install --upgrade pip\npip install databricks-cli\ndatabricks\
        \ jobs configure --version=2.1\necho ${{steps.integration-test-content.outputs.result}}\
        \ > test.json \ncat test.json\ndatabricks runs submit --json-file test.json\
        \ --wait > tmp-output.json\n# We want to extract the run id as it's useful\
        \ to show in the Github UI (as a comment).\nhead -3  tmp-output.json  | jq\
        \ '.run_id'  > run-id.json\ndatabricks runs get --run-id \"$(cat run-id.json)\"\
        \ | jq -r '.run_page_url' > run-page-url.json\necho \"run-url=$(cat run-page-url.json)\"\
        \ >> \"$GITHUB_OUTPUT\"\necho yang\n"
    - name: Create Comment with Training Model Output
      uses: actions/github-script@v6
      id: comment
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "const output = `\nThe training integration test run is available\
          \ [here](${{ steps.features-training-integration-test.outputs.run-url }}).`\n\
          \ngithub.rest.issues.createComment({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: output\n\
          })\n"
